### ISSUE TITLE
MongoDB: HPC errors

### ISSUE THREAD

**Issue by jxnl** [jxnl/TwitterAlcoholDetection#23]
### Python2.7 with MongoDB

```
[jl7500@login-0-1 Twipsy]$ module load pymongo
[jl7500@login-0-1 Twipsy]$ python
Python 2.7.6 (default, Mar 11 2014, 23:42:44)
[GCC Intel(R) C++ gcc 4.4 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __private import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__private.py", line 7, in <module>
    db = MongoClient(MongoURL).jxnl.twitter_alch
  File "/share/apps/pymongo/2.7.1/intel/lib/python2.7/site-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/mongo_client.py", line 386, in __init__
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: command SON([('authenticate', 1), ('user', u'root'), ('nonce', u'a21a3d7e222f1bec'), ('key', u'762c92cbb967e942d6d6785f57cb4830')]) failed: auth failed
```
### Python3.4 with MongoDB

```
[jl7500@login-0-1 Twipsy]$ module load python3
[jl7500@login-0-1 Twipsy]$ python3
fPython 3.4.0 (default, Apr 15 2014, 20:47:42)
[GCC Intel(R) C++ gcc 4.4 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
ro>>> from __private import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jl7500/Twipsy/__private.py", line 1, in <module>
    from pymongo import MongoClient
  File "/share/apps/pymongo/2.7.1/intel/lib/python2.7/site-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/__init__.py", line 87, in <module>
    version = get_version_string()
  File "/share/apps/pymongo/2.7.1/intel/lib/python2.7/site-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/__init__.py", line 83, in get_version_string
    if isinstance(version_tuple[-1], basestring):
NameError: name 'basestring' is not defined
```

**Comment by jxnl** [comment]
I've decided to run things on my laptop instead. since we'll have to run them again with better training data...

**Comment by rumichunara** [comment]
Ok makes sense. I enquired with HPC but that will likely take a while to
figure out.
